### ISSUE TITLE
Raytracing Roadmap

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Devsh-Graphics-Programming/Nabla#120]
## Bugs and Hacky Workaround removal
- [ ] Sporadic UIAutomationCore crash (OpenCL timeout)
- [ ] Cache the sample sequence properly (record the params) and change its locality
- [ ] Solve the weird coloured fireflies issue
- [ ] Instancing transform bugs (stuff gets thrown all over the scene)

## Minimum Usability
- [ ] Read Max Samples from the XML file
- [ ] Implement Russian Roulette and read it from the XML as well
- [ ] Robust Intersections
- [ ] Implement Rejection Sampled NEE & Multiple Importance Sampling
- [ ] Scramble key advancement
- [ ] Denoiser Integration (optionally enabled)
- [ ] Autoexposure Integration
- [ ] Tonemapping Integration
- [ ] Saving intermediate outputs when screenshotting
- [ ] Envmap light source and importance sampling
- [ ] Fast and FFT bloom choice

## Ease of Use
- [ ] Unify `raygen.comp` and `closestHit.comp`
- [ ] Extend `nbl::system` to be able to download textures and meshes over HTTP/URL
- [ ] Integrate NVENC/libvpx for producing video captures while rendering (CPU solution preferred)
- [ ] Cloud XR

## Tests
- [ ] test divergence between Mitsuba, ex 42 and ex 22 in `daily_pt.xml`
- [ ] yank up the max bounces and see if it causes a problem

## Quality and Convergence with no bias
- [ ] OBB computation for light source meshes
- [ ] Blue Noise Sampling via Heitz's techniques of scramble key ordering
- [ ] Schussler et al. BxDF fixes for bumpmaps and smooth shading normals
- [ ] CLEAR/LEADR/Toksvig (produce roughness map while mipmap filtering bumpmap)

## Easy Quality Wins
- [ ] Covariance Rendering
- [ ] Light Path Expressions || Reweighting Firefly Samples
- [ ] GSAA (increase roughness of curvy surfaces)
- [ ] A-SVGF

## Uber Quality
- [ ] ReSTIR
- [ ] Spatial and Temporal Denoising (Nvidia SDK, ProRender, Intel, Renderman-like 7 frame AI?)
- [ ] Local TMO

## Load Time Optimizations
- [ ] Converted Asset Cache
- [ ] Polyphase Mip Mapping
- [ ] `commit` on GPU Virtual Texture and Virtual Geometry

## Memory Optimizations
- [ ] Basis-U compressed prefiltered textures in the cache

## Rendering Optimizations
- [ ] Occlusion and Triangle Culling when rasterizing
- [ ] Vulkan Raytracing port
- [ ] Path Guiding
- [ ] Descriptor Indexing
- [ ] Bidirectional or Global integrators such as VCM or UBP

## Risky Optimizations
- [ ] Optimize rejection sampling to do spherical convex hulls of light source or clipping to the hemisphere
- [ ] Material Compiler made out of RTX callables
- [ ] Last Krivanek paper MIS weights out of the [0,1] range
- [ ] Replace all scene BxDFs with LTC (texturing is problematic)
- [ ] Combined product sampling of LTC and light (requires the above) probably via composed warps
- [ ] LTC product path guiding

## Endgame
- [ ] Baking (DDGI or Spherical Gaussian lightmaps)
- [ ] Animations & Temporal Tracing
- [ ] Subsurface Scattering (level up the BxDFs)
- [ ] PN-Triangle intersection
- [ ] Hair Rendering (geometry and BxDF)
- [ ] Geometry LoDs
- [ ] Out of Core Rendering (streaming Moana, here we come!)
- [ ] Spectral Rendering with Herowavelengths and resolving to multiple colourspaces simultaneously

**Comment by devshgraphicsprogramming** [comment]
albedo needs 8-10 bits of ray payload
normal needs between 16 and 32

would a good idea to subsample (lower the spp) on the AoV calculations (they're noiseless anyway)

**Comment by devshgraphicsprogramming** [comment]
# New stuff

- [ ] Register compression in Material Compiler (lots of benchmarks needed)
- [ ] Adapative Sampling (cast more rays in pixels where variance is higher)
